### ISSUE TITLE
How to add something for all HTML5 media?

### ISSUE THREAD

**Issue by Lewiscowles1986** [chriskrycho/newrustacean.com#106]
I use the following bookmarklet (minified) to allow me to adjust playback speed on third-party sites that don't give me control.

```js
javascript:(function(){
    function setAllMediaPlaybackSpeed(speed) {
        [].slice.call(document.querySelectorAll('audio,video')).map(
            function(e, idx) {
                e.playbackRate = speed;
            }
        );
    }
    var userRequestedRate = parseFloat(prompt("What playback rate would you like?"),10);
    if(!isNaN(userRequestedRate)) {
        setAllMediaPlaybackSpeed(userRequestedRate);
    }
})()
```

It'd be great to have something like this (but with nicer UI) for new rustacean (happy to PR something that sniffs the tags, then injects speed buttons underneath). Just a nice feature for any audio I feel.

Would appreciate any design guidance as otherwise it'd likely be ugly buttons or links.

**Comment by chriskrycho** [comment]
Hi @Lewiscowles1986 – thanks for the issue and the suggestion. I'm afraid I don't have the bandwidth to mentor on design guidance in detail. One suggestion that might work easily enough, though: just below the audio, add a series of links which set specific values for it, and run a simple function to set it to the matching value.

```html
<div style="text-align:center">Playback speed:
  <a href="#" onclick="setPlaybackSpeed(0.5)">0.5⨉</a> | 
  <a href="#" onclick="setPlaybackSpeed(1)">1⨉</a> | 
  <a href="#" onclick="setPlaybackSpeed(1.25)">1.25⨉</a> |
  <a href="#" onclick="setPlaybackSpeed(1.5)">1.5⨉</a> |
  <a href="#" onclick="setPlaybackSpeed(1.75)">1.75⨉</a> |
  <a href="#" onclick="setPlaybackSpeed(2)">2⨉</a>
</div>
```

That ends up looking decent:

<img width="1031" alt="screen shot 2018-03-27 at 7 02 41 am" src="https://user-images.githubusercontent.com/2403023/37969002-f1ed8d0e-318c-11e8-8304-16ea274d9d61.png">


I'd be happy to drop it on the page (and accept a PR that drops it on all the existing pages)!

**Comment by Lewiscowles1986** [comment]
i'll add it to my backlog. Don't have an ETA, but hopefully some point in April.

**Comment by chriskrycho** [comment]
That’s totally fine – obviously in no hurry here! And if you find you’re not going to get to it, you can always just come back and close this, with no hurt feelings here. Thanks again!

**Comment by Lewiscowles1986** [comment]
Would I be right in thinking to change the docs I'd need to alter Rust ~itself~ utils separate to this repo? I can't see where these docs layout or shared files are coming from. There looks like you've done some customisation already, but I couldn't find somewhere to say "in the parent layout, include {X}"

**Comment by chriskrycho** [comment]
You’d need to (a) write some CSS and then (b) [inject some HTML using the relevant rustdoc command](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#--html-in-header-include-more-html-in-head). I *believe* you can set that in the `Cargo.toml` but it’s been a while since I looked at how to do that!

**Comment by Lewiscowles1986** [comment]
`rustdoc README.md --html-after-content layout/media-playback.html` might be all I need to work out. Thanks btw, I know it's not your interest to have this, but I hope it will help other people like me that want to listen to everything at break-neck-speed, which if it does can only benefit readership :wink:

**Comment by Lewiscowles1986** [comment]
Tested :smile: 

![image](https://user-images.githubusercontent.com/2605791/38959538-f4ee894e-4358-11e8-8a2b-53b3b44c6af6.png)

**Comment by chriskrycho** [comment]
I’m actually delighted and appreciate of this, and I expect I’ll merge it later this evening. Thank you!
