### ISSUE TITLE
[minor] Sponsor contribution times are missing years

### ISSUE THREAD

**Issue by binomial0** [chriskrycho/newrustacean.com#112]
On the sponsors page, both Aaron Turon and Alexander Payne are listed to have contributed "September – March 2018". I don't know in which year's September they started, but as it's written, it reads a bit like time travel...

**Comment by chriskrycho** [comment]
Ha! Good call. I'll fix it when I release the next episode. Much obliged!

**Comment by chriskrycho** [comment]
Fixed in 9ca62bd779bb8357aecf5032f2b7aeb5ff6c8d6e!
