### ISSUE TITLE
RBR 2017 & Increasing Rust's Reach episodes unavailable

### ISSUE THREAD

**Issue by JeanMertz** [chriskrycho/newrustacean.com#113]
Hi Chris,

awesome show, been listening to it almost daily during my holiday break while learning Rust.

I've caught up to the RBR 2017 mini interviews, but unfortunately it seems those aren't available (anymore).

For example, when trying to download this URL:

https://f001.backblazeb2.com/file/newrustacean/interview/rbr_2017/jess_saxeter.mp3

Backblaze returns:

```json
{
  "code": "not_found",
  "message": "bucket newrustacean does not have file: interview/rbr_2017/jess_saxeter.mp3",
  "status": 404
}
```

Same goes for the "Increasing Rust's Reach" three-parter.

**Comment by chriskrycho** [comment]
Ahhh, I'm sure I just have bad links for those—I moved things around just a little when migrating to Backblaze! I will update later. Thank you for the report.
