### ISSUE TITLE
RSS feed link (and home page) not discoverable from e.g. https://newrustacean.com/show_notes/news/rust_1_32/

### ISSUE THREAD

**Issue by Thra11** [chriskrycho/newrustacean.com#123]
If viewing pages such as https://newrustacean.com/show_notes/news/rust_1_32/, there is no link to the rss feed for the podcast. There is also no obvious link to the homepage (clicking the logo takes you to https://newrustacean.com/show_notes/index.html)

cf. discussion on lobsters: https://lobste.rs/s/vxfth4/news_rust_1_32#c_tbmrva

**Comment by chriskrycho** [comment]
This is super helpful feedback, and one of those weird things I'd gone three years and never noticed! Sometime in the next two weeks (before the next episode is out), I'll see if I can tweak the templates a bit to (a) link back to the show home page and (b) get links to RSS, iTunes, Overcast, and Pocket Casts integrated, as I have on the home page. Thank you again for the report!

**Comment by chriskrycho** [comment]
While this is *definitely* still a discoverability issue, I've decided I'm not going to act on it given the show has wrapped up at this point. Thanks again for opening the issue!
