### ISSUE TITLE
Broken audio download link

### ISSUE THREAD

**Issue by igaray** [chriskrycho/newrustacean.com#125]
I've found an interview with a broken download links:
- [Module show_notes::cysk::_1](https://newrustacean.com/show_notes/cysk/_1/index.html)
- [Broken link](https://www.podtrac.com/pts/redirect.mp3/f001.backblazeb2.com/file/newrustacean/csyk_1.mp3)

**Comment by chriskrycho** [comment]
Thank you! I'll fix this when I publish the next episode (later today!).
