### ISSUE TITLE
Broken links to source in show notes

### ISSUE THREAD

**Issue by raindev** [chriskrycho/newrustacean.com#45]
Instead of `.html` in links there're `.html.html`.

http://www.newrustacean.com/src/show_notes/src/e009.rs.html.html#1-234
vs
http://www.newrustacean.com/src/show_notes/src/e009.rs.html#1-234

The reason for the issue is rust-lang/rust#32113, which was fixed a day ago and works fine in the latest nightly. Show notes need to be re-published after nightly upgrade.

**Comment by chriskrycho** [comment]
@raindev much obliged! I was waiting to here it was fixed before regenerating. Installing a new nightly and republishing now!

**Comment by chriskrycho** [comment]
Aaaand it's fixed!
