### ISSUE TITLE
Doc comment trails off in episode 3

### ISSUE THREAD

**Issue by reddraggone9** [chriskrycho/newrustacean.com#46]
_Wades through the archives._

Oh, what's [this](https://github.com/chriskrycho/newrustacean.com/blob/7da43821fba345bfb969d9bb428b8531037bf801/src/e003.rs#L167-177)? It looks like you didn't finish the thought.

[Rendered](http://www.newrustacean.com/show_notes/e003/fn.demonstrate_basic_enumeration.html).

**Comment by chriskrycho** [comment]
HEH! Will fix in a few. Working bonus_4 as we speak!
