### ISSUE TITLE
C example in episode 11

### ISSUE THREAD

**Issue by tmr232** [chriskrycho/newrustacean.com#47]
When talking about c being weakly typed, you give the example of adding together an integer and a character array. Of all possible example, this one is a bad example of weak typing, as the result is well defined and the operation very common. 
Conversions between integral types, including integer promotions, are probably a better example on that point. 

Btw, love the podcast!

**Comment by chriskrycho** [comment]
@tmr232, thanks for the comment and the positive feedback! Two quick responses:
1. Integral promotion is definitely another good example, and it's one I considered using. I may add it to the show notes as another example that way (and credit you for it! :wink:). But I picked the example I did for consistency with the _other_ examples in the show; being able to talk about string conversion in each case was handy.
2. You're quite right that the operation being well-defined and common. But that's part of the point I wanted to make! Coercions of all sorts (including integer promotions) _are_ both well-defined and common in C (though how well-defined obviously depends on which coercion; "Hey, undefined behavior!" is a feeling we're all familiar with, I'm sure). Similarly, this is both very well-defined and not-uncommon in JavaScript (or PHP):
   
   ``` javascript
   var a = 2;
   var b = "2";
   var c = a + b;  // '22'
   ```
   
   The fact that it's well-defined (and even a common operation) doesn't change the fact that it's a prime example of weak typing, at least to my mind!
   
   Now, of course, part of what that shows is that weak typing isn't intrinsically _bad_. It's just _implicit_. But as a friend pointed out to me recently: the explicit/implicit tradeoff is just that: a tradeoff. For my part, I prefer to land on the explicit side of that for type coercions. It's perfectly reasonable to land in a different spot there.

Thoughts? Disagreements?

Thanks in any case for listening and interacting—it's a huge part of what makes this worth doing for me. And even just in thinking through this again, my own thinking sharpened up, so much appreciated. 👍

**Comment by tmr232** [comment]
@chriskrycho, thanks for the quick reply :+1: 

I agree with your responses, and now realize that I didn't explain myself correctly.
My main point is that adding together a pointer and an integer is not coercion, at least the way I see it. In the following code sample:

``` c
int a = 2;
char b[] = "abcd";
char * c = a + b;  // "cd"
```

The variable `a` is not coerced into another type, but rather modifies the pointer. It is used in an operation, but its "value" is not present in the result. And the pointer remains a pointer (I consider the array vs. pointer difference out of scope here.)

I feel like I am missing some key vocabulary here, but this will have to do for now. I hope I made my view a bit clearer.

**Comment by chriskrycho** [comment]
@tmr232 Ah, I see what you're getting at.

Strictly speaking, of course, that's correct: pointers are just integers.

But… from where I stand, that's the thing: pointers *aren't* just integers, even though they have the same representation. They *mean* something different.

So you offered one way that behavior can go. But there's also this one:

```c
int main() {
    int a = 2;
    char b[] = "abcd";
    int c = a + b;

    printf("%s\n", c);
    printf("%d\n", c);
}
```

You'll get a warning on that first one from a good compiler (clang gets pretty grumpy about both the initialization

**Comment by chriskrycho** [comment]
@tmr232 Ah, I see what you're getting at.

Strictly speaking, of course, that's correct: pointers are just integers.

But… from where I stand, that's the thing: pointers _aren't_ just integers, even though they have the same representation. They _mean_ something different.

So you offered one way that behavior can go. But there's also this one:

``` c
#include <stdio.h>

int main() {
    int a = 2;
    char b[] = "abcd";
    int c = a + b;
    char *d = a + b;

    printf("char arithmetic: '%s'\n", d);  // "cd"
    printf("int arithmetic from char array: %d\n", c);  // random memory address + 2
    // printf("segfault, but allowed by compiler: %s\n", c);
}
```

You'll get good _warnings_ from a good C compiler about those, but you can coerce your way right into a segfault there, precisely because of the combination of integral type promotion rules and silent coercion.

I should have clarified in the show that the lattermost is what I had in mind; I wasn't thinking about the fact that you can do it _both ways_ when I wrote up the example.

Of course, they're _both_ wildly unsafe: in the example, all we have to do is make `a = 6` and we get a segfault _that_ way, too, even without the coercion. 😝 Yay for Rust!

I'll add some further comments to the show notes on this and note it in the opening of the next episode.

**Comment by chriskrycho** [comment]
@tmr232, I'm closing this for now, but I've just written up a discussion of it for part of the opening for e014 (which I'm planning to record, edit, and release tomorrow), and will link to this issue. Thanks again for the feedback and clarification—extremely helpful and very much appreciated.
