### ISSUE TITLE
a_unit or Unit?

### ISSUE THREAD

**Issue by ghost** [chriskrycho/newrustacean.com#6]
Here https://github.com/chriskrycho/newrustacean.com/blob/master/src/e003.rs#L101
Is `a_unit` supposed to be `Unit` but was left as `a_unit` due to some rename that took place from a_unit to Unit at some point? Or, I'm misunderstanding how rust works (I haven't yet started learning it)
In other words, did you mean `RelatedishThings::Unit` instead of `RelatedishThings::a_unit` ? or does that `Unit` somehow get transformed by rust into `a_unit` which would be frightening :D ?

Thanks.

**EDIT:** also this: https://github.com/chriskrycho/newrustacean.com/blob/master/src/e003.rs#L112 `AUnit` ?
**EDIT2:** I'm beginning to think it's definitely a leftover from renaming it...

**Comment by chriskrycho** [comment]
Heh, a typo indeed—I think in this case not from a rename but from an incorrect autocompletion! You're understanding correctly, and I'll push up a fix in just a minute. Much obliged!

**Comment by ghost** [comment]
Cool! Is it the same thing for `AUnit` a few lines below? https://github.com/chriskrycho/newrustacean.com/blob/master/src/e003.rs#L112

**Comment by chriskrycho** [comment]
DAGNABBIT. (Yes, it is.)
