### ISSUE TITLE
Flattr metadata in the feed (auto-flattr)

### ISSUE THREAD

**Issue by clonejo** [chriskrycho/newrustacean.com#61]
I wanted to give some hints on how to integrate metadata for Flattr which podcatchers can use to allow 'flattring' of the podcast/individual episodes manually or even automatically after an episode has been played:

Basically you add this to `<channel>`:

```
<atom:link rel="payment" title="Flattr this!"
    href="https://flattr.com/submit/auto?url=http%3A%2F%2Fnewrustacean.com%2F&amp;user_id=chriskrycho" type="text/html" />
```

And then this to each `<item>` (change the url parameter to the url of the episode's show notes of course):

```
<atom:link rel="payment" title="Flattr this!"
    href="https://flattr.com/submit/auto?url=http%3A%2F%2Fnewrustacean.com%2Fshow_notes%2Fbonus%2F_6%2F&amp;user_id=chriskrycho" type="text/html" />
```

Feed embedding is also documented [here](http://developers.flattr.net/feed/).
You can also [add more metadata](http://developers.flattr.net/auto-submit/) to the things that are flattred.

Note that I haven't tried this myself, but other podcasters are doing it the same way (eg. in [this feed](http://freakshow.fm/feed/m4a/)).

I would have written a pull request, but I could not find the code generating the feed.

**Comment by chriskrycho** [comment]
@clonejo that's awesome! I didn't realize Flattr supported it that easily. I'll see if I can integrate it into the feed this weekend.

**Comment by chriskrycho** [comment]
@clonejo I should add: I'm generating the feed semi-manually at present using [Feeder](https://reinventedsoftware.com/feeder/) to make sure I don't miss anything; I haven't yet tried to come up with a way to turn rustdoc into podcast RSS. I'm sure I _could_, but it's just more work that it's worth for the single person in the entire world doing this (me). ð
