### ISSUE TITLE
Trouble downloading Interview 2 Part 2

### ISSUE THREAD

**Issue by machineloop** [chriskrycho/newrustacean.com#66]
Hey there Chris,

Thanks again for the fantastic resource, just catching up on previous episodes; noticed I cannot seem to download Interview 2 Part 2 from the url listed in the feed:
[http://www.podtrac.com/pts/redirect.m4a/cdn.newrustacean.com/interview_2_part_2.m4a](http://www.podtrac.com/pts/redirect.m4a/cdn.newrustacean.com/interview_2_part_2.m4a)

Listening to the second half via mp3 from the show notes; it might just be the m4a...

Thanks again for such a positive contribution to the Rust community!

**Comment by machineloop** [comment]
m4a seems to be working now, maybe just a temporary connection issue, thanks!

**Comment by chriskrycho** [comment]
@brassington thanks for the note! My hosting provider for the files has had occasional dropouts like that, and I'm considering moving away from them for that reason.

Thanks for listening! Should have a new (meta) episode out in a day or two, actually. 😄
