### ISSUE TITLE
Broken feed link

### ISSUE THREAD

**Issue by ynakao** [chriskrycho/newrustacean.com#72]
The latest episode's link in XML feed is broken.   

 `<link>http://newrustacean.com/show_notes/crates_you_should_know/_2/</link>`
https://github.com/chriskrycho/newrustacean.com/commit/c3131b43dee87bf6f1921430843fab844a014678#diff-7f483546313aed892ed9333f7737bbeaR44

It should be  
`<link>http://newrustacean.com/show_notes/crates_you_should_know/_1/</link>`

Is this hard-coded? I don't know your feed generation process, so open an issue instead of pull request.

**Comment by chriskrycho** [comment]
@ynakao ah, yes. Typos, man! They're the worst! Thanks so much for finding this. I'll fix and re-upload immediately.

**Comment by chriskrycho** [comment]
Fixed in 2201286. Thanks again for the report, @ynakao!
