### ISSUE TITLE
Missing link to podcast

### ISSUE THREAD

**Issue by moshez** [chriskrycho/newrustacean.com#93]
https://github.com/chriskrycho/newrustacean.com/blob/fc6eb2f6f2663b79090fa247deb4e77a68523307/src/news/rust_1_20.rs#L34

is missing a link to 

https://request-for-explanation.github.io/podcast/

**Comment by chriskrycho** [comment]
Great catch! I’ll push a fix for this in a bit. Thank you!

**Comment by chriskrycho** [comment]
Fixed that a while back, forgot to close this. Thanks again for the catch!
